### ISSUE TITLE
Doesn't yet support full .conda package spec in regards to info and pkg sub-tars

### ISSUE THREAD

**Issue by remkade** [conda/conda-package-streaming#63]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

According to the package specification [here](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#conda-file-format), conda files are supposed to allow any type of compression supported by `libarchive` for the `pkg-*` and `info-*` sub archives. However, `conda-package-streaming` currently always expects to find `ztd` compressed tar files inside.

This may or may not be something we want to address, but reporting it here for posterity.

To replicate, put some non-zstandard compressed tar files inside your `.conda` package like so:
```bash
unzip -l mkl-2023.1.0-h6d00ec8_46342.conda
Archive:  mkl-2023.1.0-h6d00ec8_46342.conda
  Length      Date    Time    Name
---------  ---------- -----   ----
    16833  01-01-1980 00:00   info-mkl-2023.1.0-h6d00ec8_46342.tar.lz4
276985433  01-01-1980 00:00   pkg-mkl-2023.1.0-h6d00ec8_46342.tar.lz4
       31  04-18-2023 07:12   metadata.json
---------                     -------
277002297                     3 files
```

Then try to install that conda file:
```bash
conda install ./mkl-2023.1.0-h6d00ec8_46342.conda

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 344, in _make_single_record
        repodata_record = read_repodata_json(extracted_package_dir)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/gateways/disk/read.py", line 138, in read_repodata_json
        with open(join(extracted_package_directory, 'info', 'repodata_record.json')) as fi:
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/common/compat.py", line 63, in open
        return io_open(file, str(mode), buffering=buffering,
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/kleaders/anaconda3/pkgs/mkl-2023.1.0-h6d00ec8lz4_46342/info/repodata_record.json'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 364, in _make_single_record
        raw_json_record = read_index_json(extracted_package_dir)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/gateways/disk/read.py", line 124, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/common/compat.py", line 63, in open
        return io_open(file, str(mode), buffering=buffering,
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/kleaders/anaconda3/pkgs/mkl-2023.1.0-h6d00ec8lz4_46342/info/index.json'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/notices/core.py", line 121, in wrapper
        return func(*args, **kwargs)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/cli/install.py", line 176, in install
        explicit(args_packages, prefix, verbose=not context.quiet)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/misc.py", line 92, in explicit
        pfe.execute()
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 707, in execute
        self.prepare()
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 686, in prepare
        self.paired_actions.update(
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 687, in <genexpr>
        (prec, self.make_actions_for_record(prec)) for prec in self.link_precs
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 554, in make_actions_for_record
        extracted_pcrec = next(
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 555, in <genexpr>
        (
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 558, in <genexpr>
        PackageCacheData(pkgs_dir).query(pref_or_spec)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 153, in query
        return (pcrec for pcrec in self._package_cache_records.values() if param.match(pcrec))
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 282, in _package_cache_records
        self.load()
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 123, in load
        package_cache_record = self._make_single_record(base_name)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 389, in _make_single_record
        extract_tarball(package_tarball_full_path, extracted_package_dir)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda/gateways/disk/create.py", line 215, in extract_tarball
        conda_package_handling.api.extract(tarball_full_path, dest_dir=destination_directory)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda_package_handling/api.py", line 77, in extract
        format.extract(fn, dest_dir, components=components)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda_package_handling/conda_fmt.py", line 46, in extract
        _extract(str(fn), str(dest_dir), components=components)
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda_package_handling/streaming.py", line 35, in _extract
        stream = package_streaming.stream_conda_component(
      File "/Users/kleaders/anaconda3/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py", line 105, in stream_conda_component
        raise LookupError(f"didn't find {component_name} component in {filename}")
    LookupError: didn't find info-mkl-2023.1.0-h6d00ec8lz4_46342 component in /Users/kleaders/anaconda3/pkgs/mkl-2023.1.0-h6d00ec8lz4_46342.conda

`$ /Users/kleaders/anaconda3/bin/conda install ./mkl-2023.1.0-h6d00ec8_46342.conda`
```

### Conda Info

```shell
active environment : lz4_testing
    active env location : /Users/kleaders/anaconda3/envs/lz4_testing
            shell level : 2
       user config file : /Users/kleaders/.condarc
 populated config files : 
          conda version : 23.3.1
    conda-build version : 3.23.3
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.3.1=0
                          __unix=0=0
       base environment : /Users/kleaders/anaconda3  (writable)
      conda av data dir : /Users/kleaders/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/kleaders/anaconda3/pkgs
                          /Users/kleaders/.conda/pkgs
       envs directories : /Users/kleaders/anaconda3/envs
                          /Users/kleaders/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.9 Darwin/22.4.0 OSX/13.3.1
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

**Comment by remkade** [comment]
Appears to be related to this line:
https://github.com/conda/conda-package-streaming/blob/main/conda_package_streaming/package_streaming.py#L107

**Comment by dholth** [comment]
We will need to update the specification to allow zstd only. It's understandable that they were excited about libarchive's flexibility when designing the format, but only zstd has ever been implemented. http://facebook.github.io/zstd/ shows that zstd is extremely fast to decompress.
